name: Issues

on: [issues]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          args: "RFC"