name: Houston

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Prepare Env
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Publish
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run publish --ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      # - name: Create Tag
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
