name: Houston

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Setup NPM Registry
        run: echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > .npmrc && npm config get registry && npm whoami
      - name: Prepare Env
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Publish
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: run publish --ci
      # - name: Create Tag
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
