name: Pull Request

on: [pull_request]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - uses: kceb/pull-request-url-action@v1
        id: pr-url
      - name: Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          args: "@Aldebaran 🦖  Nova PullRequest: ${{ github.context.payload.pull_request.title }} \n${{ steps.pr-url.outputs.url }}"
      - name: Prepare Env
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Linter
        run: yarn lint
