name: Publish

on: [pull_request]

jobs:
  check-lint:
    needs: check-version
    runs-on: ubuntu-latest
    if: needs.check-version.outputs.BETA == 'false'
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Prepare Env
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Publish
        run: yarn lint
