name: Request For Comments

on: 
  project_card: 
    types: ["created", "moved", "converted", "edited"]

jobs:
  request-for-comments:
    runs-on: ubuntu-latest
    steps:
      - name: data
        run: echo "${{toJSON(github.event)}}"
      - name: Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          args: "RFC ${{toJSON(github.event)}}"